### ISSUE TITLE
Relationships/Nodes aren't being parsed properly

### ISSUE THREAD

**Issue by freeeve** [AnormCypher/AnormCypher#3]
``` Scala
Cypher("start n=node(*) return n.name as name, n")().map {
     case CypherRow(name: String, n: org.anormcypher.NeoNode) => name -> n
}
```

fails with an exception:

```
scala.MatchError: Row('ColumnName(name,None)':AnormCypher as String, 'ColumnName(n,None)':{outgoing_relationships=http://localhost:7474/db/data/node/1144/relationships/out, data={name=AnormCypher}, traverse=http://localhost:7474/db/data/node/1144/traverse/{returnType}, all_typed_relationships=http://localhost:7474/db/data/node/1144/relationships/all/{-list|&|types}, property=http://localhost:7474/db/data/node/1144/properties/{key}, self=http://localhost:7474/db/data/node/1144, properties=http://localhost:7474/db/data/node/1144/properties, outgoing_typed_relationships=http://localhost:7474/db/data/node/1144/relationships/out/{-list|&|types}, incoming_relationships=http://localhost:7474/db/data/node/1144/relationships/in, extensions={}, create_relationship=http://localhost:7474/db/data/node/1144/relationships, paged_traverse=http://localhost:7474/db/data/node/1144/paged/traverse/{returnType}{?pageSize,leaseTime}, all_relationships=http://localhost:7474/db/data/node/1144/relationships/all, incoming_typed_relationships=http://localhost:7474/db/data/node/1144/relationships/in/{-list|&|types}} as String) (of class org.anormcypher.CypherResultRow)
    at $anonfun$1.apply(<console>:11)
    at $anonfun$1.apply(<console>:11)
    at scala.collection.immutable.Stream.map(Stream.scala:175)
    at .<init>(<console>:11)
    at .<clinit>(<console>)
    at .<init>(<console>:11)
    at .<clinit>(<console>)
    at $print(<console>)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:704)
    at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:914)
    at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:546)
    at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:577)
    at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:543)
    at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:694)
    at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:745)
    at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:712)
    at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:745)
    at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:712)
    at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:745)
    at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:651)
    at scala.tools.nsc.interpreter.ILoop.processLine$1(ILoop.scala:542)
    at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:550)
    at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:822)
    at scala.tools.nsc.interpreter.ILoop.main(ILoop.scala:851)
    at xsbt.ConsoleInterface.run(ConsoleInterface.scala:57)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:57)
    at sbt.compiler.AnalyzingCompiler.console(AnalyzingCompiler.scala:48)
    at sbt.Console.console0$1(Console.scala:23)
    at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply$mcV$sp(Console.scala:24)
    at sbt.TrapExit$.executeMain$1(TrapExit.scala:33)
    at sbt.TrapExit$$anon$1.run(TrapExit.scala:42)
```

**Comment by spkenn5** [comment]
hey @freeeve what was the solution for this issue? I am currently having the same one..

**Comment by Kai-Chen** [comment]
The node and relationship mapping was working up to 0.8.1.  The 0.9 release switched to the transactional endpoint, as the legacy endpoint is deprecated.  And in Neo4j 2.x this endpoint is not returning the node and relationship meta data correctly, so we dropped the feature on our end as well.  Neo4j 3.x seems to be returning the meta in the transactional endpoint, but we haven't added back the mapping code yet.  But it looks like we should get a 0.9.2 release out to get this done.

In the meantime, if you use 0.8.1 it should work with Neo4j 2 servers.

Cheers!

**Comment by spkenn5** [comment]
```
scala.MatchError: CypherResultRow('n':Map(paged_traverse -> http://127.0.0.1:7474/db/data/node/81928/paged/traverse/{returnType}{?pageSize,leaseTime}, all_relationships -> http://127.0.0.1:7474/db/data/node/81928/relationships/all, outgoing_typed_relationships -> http://127.0.0.1:7474/db/data/node/81928/relationships/out/{-list|&|types}, data -> Map(name -> Kenji, location -> Indonesia), self -> http://127.0.0.1:7474/db/data/node/81928, outgoing_relationships -> http://127.0.0.1:7474/db/data/node/81928/relationships/out, create_relationship -> http://127.0.0.1:7474/db/data/node/81928/relationships, extensions -> Map(), properties -> http://127.0.0.1:7474/db/data/node/81928/properties, incoming_relationships -> http://127.0.0.1:7474/db/data/node/81928/relationships/in, labels -> http://127.0.0.1:7474/db/data/node/81928/labels, traverse -> http://127.0.0.1:7474/db/data/node/81928/traverse/{returnType}, incoming_typed_relationships -> http://127.0.0.1:7474/db/data/node/81928/relationships/in/{-list|&|types}, metadata -> Map(id -> 81928, labels -> ListBuffer(Student)), property -> http://127.0.0.1:7474/db/data/node/81928/properties/{key}, all_typed_relationships -> http://127.0.0.1:7474/db/data/node/81928/relationships/all/{-list|&|types}) as String) (of class org.anormcypher.CypherResultRow)
	at handler.DataHandler$$anonfun$7.apply(DataHandler.scala:162) ~[classes/:na]
	at handler.DataHandler$$anonfun$7.apply(DataHandler.scala:162) ~[classes/:na]
	at scala.collection.immutable.Stream.map(Stream.scala:418) ~[scala-library-2.11.8.jar:na]
	at handler.DataHandler.getTest(DataHandler.scala:162) ~[classes/:na]
	at service.DataService.getUserById(DataService.scala:66) ~[classes/:na]
	at controllers.Application$$anonfun$getUserFromNeo4j$1.apply(Application.scala:37) ~[classes/:na]
	at controllers.Application$$anonfun$getUserFromNeo4j$1.apply(Application.scala:36) ~[classes/:na]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:408) ~[play_2.11-2.4.6.jar:2.4.6]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:407) ~[play_2.11-2.4.6.jar:2.4.6]
	at play.api.mvc.Action$.invokeBlock(Action.scala:533) ~[play_2.11-2.4.6.jar:2.4.6]
	at play.api.mvc.Action$.invokeBlock(Action.scala:530) ~[play_2.11-2.4.6.jar:2.4.6]
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493) ~[play_2.11-2.4.6.jar:2.4.6]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[play_2.11-2.4.6.jar:2.4.6]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[play_2.11-2.4.6.jar:2.4.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.4.6.jar:2.4.6]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104) ~[play_2.11-2.4.6.jar:2.4.6]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103) ~[play_2.11-2.4.6.jar:2.4.6]
	at scala.Option.map(Option.scala:146) ~[scala-library-2.11.8.jar:na]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103) ~[play_2.11-2.4.6.jar:2.4.6]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96) ~[play_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:741) ~[play-iteratees_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:741) ~[play-iteratees_2.11-2.4.6.jar:2.4.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [scala-library-2.11.8.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [scala-library-2.11.8.jar:na]
	... 6 common frames omitted
```

I am currently using 0.6.0, and using the exact same code as mentioned above.
