### ISSUE TITLE
Cannot query data with neo4j 3.2.1

### ISSUE THREAD

**Issue by git4sun** [AnormCypher/AnormCypher#67]
New to this project. When I try this code:
`
    
    val query = Cypher(
      """
        |MATCH (tom:Person {name: "Tom Hanks"})-[:ACTED_IN]->(tomHanksMovies) RETURN tom,tomHanksMovies
      """.stripMargin
    )

    val rs  = query.apply.map(row=>
      row[String]("tom") -> row[String]("tomHanksMovies")
    )
    println(rs)
`

I got the following exception:

> Exception in thread "main" java.lang.RuntimeException: Expected '[' but got '"' / chr(34)
	at scala.sys.package$.error(package.scala:27)
	at play.api.libs.iteratee.Iteratee$$anonfun$run$1.apply(Iteratee.scala:396)
	at play.api.libs.iteratee.Iteratee$$anonfun$run$1.apply(Iteratee.scala:389)
	at play.api.libs.iteratee.StepIteratee$$anonfun$fold$2.apply(Iteratee.scala:706)
	at play.api.libs.iteratee.StepIteratee$$anonfun$fold$2.apply(Iteratee.scala:706)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:120)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Any help on getting started with it will be greatly appreciated. Thanks!

**Comment by corykim** [comment]
Is the machine that is running this code configured to use a proxy? If so, the proxy will attempt to connect to the neo4j host. If it can't connect, you will get some kind of error, such as 404. To solve this, you can *one of the following:*

- Disable HTTP proxy on this machine, *or*
- Configure your machine *not* to proxy the neo4j host, *or*
- Add the JVM parameter `-Dhttp.nonProxyHosts=<your-neo4j-host>`
